[package]
name = "rxprog"
version = "0.1.0"
authors = ["The6P4C <watsonjcampbell@gmail.com>"]
edition = "2018"

[dev-dependencies]
mock-io = { git = "https://github.com/carllerche/mock-io", default-features = false, features = [] }
