[package]
name = "rxprog-cli"
version = "0.1.0"
authors = ["The6P4C <watsonjcampbell@gmail.com>"]
edition = "2018"

[workspace]
members = ["rxprog"]

[dependencies]
clap = "~2.27.0"
rxprog = { path = "rxprog" }
serialport = "3.3.0"
